### 2. 배열의 생성과 변형

In [1]:
import numpy as np

- 자료형

In [2]:
x = np.array([1,2,3])
x.dtype

dtype('int32')

In [3]:
x = np.array([1.,2.,3.])
x.dtype

dtype('float64')

In [5]:
# 원소의 데이터 타입이 모두 같아야 함
x = np.array([1,2,3.])
x.dtype

dtype('float64')

In [7]:
x = np.array([1,2,3], dtype='int8')
x.dtype

dtype('int8')

- Inf / NaN

In [9]:
import warnings
warnings.filterwarnings('ignore')
np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])

array([  0.,  inf, -inf,  nan])

In [11]:
np.log(0), np.exp(-np.inf)

(-inf, 0.0)

- 배열 생성

In [12]:
# zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [15]:
# ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [18]:
np.ones((2,2,2),dtype=int)

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [19]:
# *_like : shape와 type 일치
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.zeros_like(a)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [20]:
np.ones_like(a)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [23]:
# empty
g = np.empty((4,3))
g

array([[1.01855798e-312, 1.08221785e-312, 1.01855798e-312],
       [9.54898106e-313, 1.03977794e-312, 1.01855798e-312],
       [1.23075756e-312, 1.18831764e-312, 1.06099790e-312],
       [9.76118064e-313, 1.06099790e-312, 1.90979621e-312]])

In [24]:
for i in range(12):
    g[i//3,i%3] = i
g

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

- arange: numpy의 range

In [25]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [27]:
np.arange(1,2,0.1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])