### 5. 난수 발생과 카운팅

In [1]:
import numpy as np

- Seed 설정

In [2]:
np.random.seed(2023)
np.random.random(5)

array([0.3219883 , 0.89042245, 0.58805226, 0.12659609, 0.14134122])

- 데이터의 순서 바꾸기

In [3]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.random.shuffle(x)
x

array([7, 4, 3, 2, 8, 9, 1, 6, 0, 5])

- 데이터 샘플링

In [5]:
np.random.choice(5, 5,replace=False)

array([3, 4, 0, 2, 1])

In [7]:
x = np.random.randint(1,100,10)
x

array([71, 16, 89, 73, 48, 66, 72, 23, 54,  8])

In [8]:
np.random.choice(x,5,replace=False)

array([54,  8, 23, 72, 73])

- 난수 생성

In [9]:
# random() - Uniform 분포, 0 ~ 1 사이의 값
np.random.random(10)

array([0.59310305, 0.9147945 , 0.25066314, 0.07173657, 0.30121014,
       0.26788935, 0.72442186, 0.4034967 , 0.47762815, 0.21232418])

In [10]:
# randint(low,high,N) - [low high)
np.random.randint(1,7,10)

array([4, 6, 2, 4, 5, 4, 6, 6, 2, 5])

In [11]:
# normal(평균, 표준편차, N) - 정규분포
np.random.normal(170,10,10)

array([157.48804459, 166.55865928, 180.86199825, 172.62609705,
       169.99914394, 177.58645897, 167.26943945, 147.39058082,
       172.02856304, 170.06243698])

In [12]:
# randn(N) - 표준정규분포 N(0, 1)
np.random.randn(10)

array([-0.69789635,  1.3179999 , -1.3305147 ,  1.84333885,  0.07586461,
       -0.88877486,  0.72900879,  0.17879745,  0.79162212, -0.51695485])

In [13]:
# binomial (시도횟수, 평균, N) - 이항분포 B(N, p)
np.random.binomial(10,0.5,20).reshape(4,5)

array([[5, 2, 4, 5, 2],
       [6, 4, 6, 6, 4],
       [6, 5, 7, 5, 5],
       [5, 6, 3, 6, 7]])

In [14]:
# 가설 검정: t - 검정
# standard_t(자유도, N)
np.random.standard_t(2,10)

array([ 2.6474858 ,  0.11196557,  2.47395645, -1.38920435, -0.87036697,
        0.37764753, -1.24874601, -0.56429419, -1.74308619, -0.00891616])

In [30]:
# 3-5-1
x_ = np.random.binomial(1,0.5,10)
x_

array([1, 0, 0, 0, 0, 1, 1, 0, 1, 1])

In [88]:
x_1 = np.random.randint(1,7,100)
x_1.mean()

3.68

In [101]:
# 3-5-2
money = 10000
for _ in range(250):
    money = int(money + (money * np.random.normal(0,0.01)))
print(f'{money:,d}')

10,359


In [112]:
money = 10000
for _ in range(1,101):
    money = int(money + (money * np.random.normal(0,0.01)))
    print(f'{money:,d}')

10051
10083
9882
9849
10066
10005
9833
10042
10072
10112
10108
9986
10093
10100
10115
9914
9956
9841
10347
9968
9961
10186
9915
10009
10018
9904
9999
9794
10268
9840
9874
9893
9829
9929
10035
10193
10004
9998
10155
9966
9986
9925
10021
10033
10081
9895
9960
9994
9970
9995
9998
9937
9984
9793
10080
10014
10002
9871
9960
10215
10009
10007
9937
9968
9932
10010
9932
10076
9874
10064
9870
10045
10078
10066
9980
10012
9931
10049
10065
10000
10080
10047
10131
10043
9994
10013
10104
10006
9857
10077
9956
10173
10142
9741
9954
10132
9885
10051
10049
9917


In [118]:
rate = np.random.normal(0,0.01,101)
price = 10000
price = price + price * rate[0]

In [119]:
price = 10000
for i in range(101):
    price = price * (1 + rate[i])
    price = int(np.round(price))
    print(price,end=' ')

10041 9868 9923 9843 9863 9751 9571 9642 9493 9431 9325 9485 9392 9301 9248 9268 9367 9311 9279 9208 9251 9238 9269 9281 9407 9473 9349 9224 9080 9210 9116 9137 9184 9146 9070 9053 9046 8967 8898 8909 8829 8664 8620 8531 8627 8770 8730 8722 8741 8653 8644 8612 8564 8469 8416 8375 8289 8270 8216 8114 8133 8098 8077 8144 8033 8006 8041 8012 7946 7868 7916 8026 8082 8102 8078 8044 7924 7929 7859 7802 7675 7827 7761 7756 7709 7675 7869 7785 7768 7912 7823 7894 7873 8018 8043 8008 8013 8078 8105 8148 8243 

In [120]:
np.random.seed(2023)
rate = np.random.normal(0,0.01,250)
rate[:5]

array([ 0.00711674, -0.00324485, -0.01001871,  0.00236251, -0.0010216 ])

In [122]:
# 1. 리스트로 해결
price = 10000
price_list = []
for i in range(250):
    price = price * (1 + rate[i])
    price = int(np.round(price))
    price_list.append(price)
price_array = np.array(price_list)
price_array[-10:]

array([10814, 10893, 10674, 10645, 10588, 10724, 10739, 10686, 10691,
       10497])

In [128]:
# 2. Array 로 해결
price_array_2 = np.zeros(250, dtype=int)
price = 10000
for i in range(250):
    price = price * (1 + rate[i])
    price = int(np.round(price))
    price_array_2[i] = price
price_array_2[-10:]

array([10814, 10893, 10674, 10645, 10588, 10724, 10739, 10686, 10691,
       10497])

- 데이터 카운팅

In [129]:
dices = np.random.randint(1,7,100)
np.unique(dices)

array([1, 2, 3, 4, 5, 6])

In [130]:
np.unique(dices,return_counts=True)

(array([1, 2, 3, 4, 5, 6]), array([ 9, 24, 24, 13, 15, 15], dtype=int64))

In [132]:
indices, count = np.unique(dices,return_counts=True)
indices, count

(array([1, 2, 3, 4, 5, 6]), array([ 9, 24, 24, 13, 15, 15], dtype=int64))

In [133]:
indices*count

array([ 9, 48, 72, 52, 75, 90], dtype=int64)

In [138]:
sum(indices*count)/sum(count)

3.46

In [136]:
np.mean(dices)

3.46

In [140]:
aa = np.array(['a', 'b', 'c', 'a'])
index, count = np.unique(aa, return_counts=True)
index, count

(array(['a', 'b', 'c'], dtype='<U1'), array([2, 1, 1], dtype=int64))

In [141]:
np.bincount(dices, minlength=6)     # 0~ 6

array([ 0,  9, 24, 24, 13, 15, 15], dtype=int64)